### ISSUE TITLE
More quotes 

### ISSUE THREAD

**Issue by duramato** [apsun/QuoteLock#1]
Hey first of all cool app,  really like the concept. 
Secondly could you add support for quotes from example books, games and movies  from "western"  culture as u don't speak Japanese(?)  :P 
Also I saw the update with the server not being able to handle all requests,  something  you  could try do is create a github repo (or a file in here) with the quotes in a file and just point your app to its raw  version

**Comment by apsun** [comment]
To be honest I wasn't planning on releasing this app - it was originally made as a demo/test for one of my Android libraries, but that was kind of boring so I decided to hook it up to my VNaaS backend. If the demand for more quote variety is high enough I suppose I could add them if I have some free time. Currently though I'm content with keeping it as it as.

Also, my quote database currently holds 200 thousand lines, I don't think storing them in a text file is a good idea :-p

**Comment by duramato** [comment]
You could split them in to seperate files or something similiar :P , and could still be in json format.
Examples from where i "got" the idea of the github files/repo:
https://github.com/SickRage/sickrage.github.io/blob/master/scene_exceptions/scene_exceptions.json
https://github.com/SickRage/sickrage.github.io/blob/master/sb_network_timezones/network_timezones.txt

**Comment by DaniPhii** [comment]
I don't speak Japanese but I love this app, if we were able to use our own files of quotes as an alternative, it would be so nice. That way the app or quotes wouldn't have to be translated, everyone could use their own feed. :D

**Comment by apsun** [comment]
Interesting idea. Where would the quotes come from, though? I don't think the average user has a huge list of quotes just lying around somewhere :-p

**Comment by duramato** [comment]
https://www.google.com/search?q=popular+quotes+rss+feed
whorth a shot :P 
that way you could just add an xml parser to read them, and possibly sleecting one at random.

**Comment by DaniPhii** [comment]
I agree, @duramato, XML is so powerful and that way we may choose Google domain and language (com, co.uk, es, mx) to make it possible and satisfying everyone. :)

**Comment by apsun** [comment]
I've added a few sources, so I'm closing this issue now -- if you have any additional quote providers you wish to include, please create a separate new issue for each. Thanks.
