### ISSUE TITLE
Can't use hitokoto source

### ISSUE THREAD

**Issue by misaka00251** [apsun/QuoteLock#11]
Always can't download quote even I use shadowsocks.

**Comment by apsun** [comment]
Well, that would be because their server is offline (you can visit [hitokoto.us](http://www.hitokoto.us/) to see for yourself), I can't do anything about it :-(

The only provider I control is Visual Novel as a Service, all of the other ones are third party.

**Comment by apsun** [comment]
Fixed in 313077bea2c364269c621f18d1163e6702c7a866 by using an unofficial source. Looks like the official website is down for good.
