### ISSUE TITLE
German Quotes

### ISSUE THREAD

**Issue by Flolant** [apsun/QuoteLock#13]
Hello,
is it possible to add some german quote sources?
Some sources:
http://zitate.net/
http://www.zitate.de/
http://natune.net/zitate/
https://www.zitate.eu/search

I found no api on all sites.
Thank you 
Flolant

**Comment by apsun** [comment]
Sorry for the late reply, I've been swamped with homework these past few weeks. I've added Natune.net as a source in v1.3.0, it seems to be the only site on your list that lets users get a random quote. 69d984e7c0b41b933c7df326762a09f3cb8270d5
