### ISSUE TITLE
Quotes in Spanish

### ISSUE THREAD

**Issue by pacmankillers** [apsun/QuoteLock#3]
I love this module it,s amazing, thanks to all team for our work.

I request a Quotes in Spanish, the mayor source its  freakuotes. com 

Thanks for your support and i use this app in all my mobiles.

Grettings from México

**Comment by apsun** [comment]
Sure :-)

Is there an API to access the quotes? If not then I will have to do HTML scraping.

**Comment by pacmankillers** [comment]
I dont, know, i check the page but i seem no api :/

Date: Thu, 2 Jun 2016 22:15:05 -0700

**Comment by apsun** [comment]
Added in the latest version! Will be released in `v1.2.0` soon.

**Comment by pacmankillers** [comment]
Thanks n.n great module. It has in all my devices forever n.n

**Comment by DaniPhii** [comment]
Thanks a lot! I love this module, now I can manually put tweets as a feed of quotes, hahaha… Great version 1.2.0! :D
